### ISSUE TITLE
Deleting Redirect is not possible

### ISSUE THREAD

**Issue by thepalk** [alt-design/Alt-Redirect-Addon#1]
https://workspace.palk.co/T91XSsb394KlnzlfJzWJ

Hi there! I've encountered an issue where attempting to delete a redirect through the control panel isn't functioning correctly on both Safari and Chrome browsers.

**Comment by Alt-Ben** [comment]
Hey!

Have you got any errors in the console?

**Comment by thepalk** [comment]
[Error] Failed to load resource: the server responded with a status of 404 () (delete, line 0)
/alt-design/alt-redirect/delete

**Comment by Alt-Ben** [comment]
Give it an update and another go now!

**Comment by thepalk** [comment]
It’s gone now entirely. No error message. :D

**Comment by Alt-Ben** [comment]
Ahaa amazing 😅 - just pushed another update, give it a go now!

**Comment by thepalk** [comment]
I’m sorry, still nothing.

**Comment by Alt-Ben** [comment]
That's weird - have you checked it's not the cache etc? I've just done a clean install here and it seems okay?

Have you got anything in the console error logs (screenshots etc would be awesome if you have them)

**Comment by thepalk** [comment]
Thank you, seems to work now!

**Comment by Alt-Ben** [comment]
Ah amazing! Thanks for bearing with! :)
