### ISSUE TITLE
Trailing slashes

### ISSUE THREAD

**Issue by RobMaple** [alt-design/Alt-Redirect-Addon#11]
Is there any way to make from URLs match with an optional trailing slash?
Currently if I set '/old' to redirect to '/new' it won't match a request for '/old/'.

Currently I'm adding both versions of the path but am wondering if this could be done more succinctly.

**Comment by Alt-Ben** [comment]
Hey Rob!

We've addressed this in the latest release - hopefully that's okay!

Cheers,
