### ISSUE TITLE
Long URLs move delete buttons out of view

### ISSUE THREAD

**Issue by patrickhoehn** [alt-design/Alt-Redirect-Addon#4]
Long URLs move delete buttons out of view.
<img width="929" alt="Screenshot" src="https://github.com/alt-design/Alt-Redirect-Addon/assets/17851700/fd587f27-c58c-47f1-9389-de5298f936b1">

**Comment by benmAltDesign** [comment]
Hi there.

I've addressed this in commit db3cd75 and it will be in the next release.

Thank you
